language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y g++
  - sudo apt-get install -y yasm
  - sudo apt-get install -y libsdl2-dev
  - wget "https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-Linux-x86_64.tar.gz"
  - tar zxvf cmake-3.22.1-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.22.1-Linux-x86_64/bin:$PATH

  - make cicadaPlayer -j8

  before_script:
    - mkdir build
    - cd build
    - cmake

  script: make